# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.

# JupyterHub docker-compose configuration file
version: "2.3"

services:
  jupyter:
    build:
      context: .
    image: jupyterhub
    container_name: jupyterhub  # necessary so spawned containers can reach hub
    depends_on:
      - jupyter-db
    restart: unless-stopped
    runtime: nvidia
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
      # volume for Jupyter Hub database and cookie secrets
      - "jupyter-data:/data"
      # configs
      - "./data/configs/:/srv/jupyterhub/"
    networks:
      - default
      - jupyter-network
    ports:
      - 8080:80
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      # JupyterHub will spawn this Notebook image for users
      DOCKER_NOTEBOOK_IMAGE: hub-deep-learning-notebook-gpu
      # specify how GPUs are exposed to containers
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
      # Postgres db info
      POSTGRES_DB: jupyterhub
      POSTGRES_HOST: jupyterhub-db
      # use `openssl rand -hex 32` to generate, and copy it down below
      POSTGRES_PASSWORD: changeme
    command: >
      jupyterhub -f /srv/jupyterhub/jupyterhub_config.py
  jupyter-db:
    image: postgres:9.5
    restart: unless-stopped
    container_name: jupyterhub-db
    networks:
      - jupyter-network
    environment:
      POSTGRES_DB: jupyterhub
      POSTGRES_PASSWORD: changeme
    volumes:
      - "jupyter-db:/var/lib/postgresql/data"

networks:
  default:
  jupyter-network:
    name: jupyter-network  # specified so that spawned containers can join
volumes:
  jupyter-data:
  jupyter-db:
