version: "3.9"

services:
  jupyter:
    image: jupyterhub:latest
    container_name: jupyterhub  # necessary so spawned containers can reach hub
    restart: unless-stopped
    runtime: nvidia
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
      # volume for Jupyter Hub database and cookie secrets
      - "jupyter-data:/data"
      # configs
      - "./data/configs/:/srv/jupyterhub/"
    networks:
      - default
      - jupyter-network
    ports:
      - 8080:80
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      # JupyterHub will spawn this Notebook image for users
      DOCKER_NOTEBOOK_IMAGE: hub-deep-learning-notebook-gpu
      # specify how GPUs are exposed to containers
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
      GITHUB_CLIENT_ID: changeme
      GITHUB_CLIENT_SECRET: changeme
    command: >
      jupyterhub -f /srv/jupyterhub/jupyterhub_config.py

networks:
  default:
  jupyter-network:
    name: jupyter-network  # specified so that spawned containers can join
volumes:
  jupyter-data:
